server:
  port: 8096

spring:
  application:
    name: msvc-formadepago
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db.tseqkdyltupklalpgtki.supabase.co:5432/postgres
    username: postgres
    password: 1997Guallaba
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka